version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
  api:
    build:
      "./"
    ports:
      - "8000:8000"
    depends_on:
      - db
  waha:
    image: devlikeapro/waha:latest
    container_name: waha-container
    restart: always
    ports:
      - "3000:3000"